workflows:
  kmp-build:
    name: KMP Build
    max_build_duration: 120 # KMP builds can take longer
    instance_type: mac_mini # Or your preferred instance type

    # No explicit JAVA_HOME unless ABSOLUTELY necessary
    environment:
      xcode: latest

    scripts:
      - name: Set up Gradle Cache (Optional, but HIGHLY recommended)
        script: |
          mkdir -p $HOME/.gradle/caches/modules-2/files-2.1
          chmod -R a+w $HOME/.gradle/caches/modules-2

      - name: Show system info
        script: |
          #!/bin/bash
          echo "Codemagic Environment Info:"
          echo "OS: $(uname -s) $(uname -r) $(uname -m)"
          echo "Java Version:"
          java -version
          echo "Gradle Version:"
          ./gradlew --version
          echo "Kotlin Version:"
          ./gradlew kotlinVersion

      - name: Clean and Validate Gradle Wrapper
        script: |
          ./gradlew clean build -m --write-locks # Clean, build, module-wise, write lock
          ./gradlew dependencies --write-locks # Check dependencies
          ./gradlew buildEnvironment # Debug build environment

      - name: Run KMP Tests
        script: ./gradlew allTests

      - name: Build Android APK
        script: ./gradlew assembleRelease

      - name: Build iOS Framework
        script: ./gradlew :shared:assembleReleaseFramework # More specific task

    artifacts:
      - build/**/outputs/**/*.apk
      - shared/build/outputs/iosArm64/release/*.framework
      - shared/build/outputs/iosX64/release/*.framework # Include x86_64 for simulators

    cache:
      paths:
        - $HOME/.gradle/caches/modules-2/files-2.1
        - $HOME/.gradle/caches/transforms-3
