workflows:
  kmp-default:
    name: KMP Android Default Workflow
    environment:
      java: 17
    scripts:
      - name: Build Android app
        script: ./gradlew :androidApp:assembleDebug

      - name: Run tests
        script: ./gradlew test

    artifacts:
      - androidApp/build/outputs/**/*.apk
      - androidApp/build/outputs/**/*.aab
