workflows:
  kmp-default:
    name: KMP Android Default Workflow
    environment:
      java: 17
    scripts:
      - name: Permitir execução do Gradle Wrapper
        script: chmod +x ./gradlew

      - name: Build Android app
        script: ./gradlew :composeApp:assembleDebug

      - name: Run tests
        script: ./gradlew test

    artifacts:
      - composeApp/build/outputs/**/*.apk
      - composeApp/build/outputs/**/*.aab
