workflows:
  kmp-android-workflow:
    name: Kotlin Multiplatform - Android Build
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.seuapp.kmp"
        JAVA_VERSION: 17
      android_signing:
        - your_keystore_reference  # você configura isso nas Configurações do Codemagic
      groups:
        - google_credentials  # se precisar publicar na Play Store
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
    scripts:
      - name: Configurar Java
        script: |
          sdk install java $JAVA_VERSION
          sdk use java $JAVA_VERSION

      - name: Build do projeto KMP para Android
        script: |
          ./gradlew :androidApp:assembleRelease

      - name: Testes unitários
        script: |
          ./gradlew test

    artifacts:
      - build/outputs/**/*.apk
      - build/outputs/**/*.aab
