workflows:
  kmp-build:
    name: KMP Build Workflow
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /opt/java/openjdk17
      android: true
      xcode: latest
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Run KMP Tests
        script: ./gradlew allTests
      - name: Build Android APK
        script: ./gradlew assembleRelease
      - name: Build iOS Framework
        script: ./gradlew :shared:build
    artifacts:
      - build/**/outputs/**/*.apk
      - shared/build/bin/iosArm64/releaseFramework/*.framework
