workflows:
  kmp-build:
    name: KMP Build Workflow
    max_build_duration: 60
    instance_type: mac_mini 
    environment:
      JAVA_HOME: "${JAVA_HOME}"  
     # JAVA_HOME: "/opt/android/java/openjdk17" # ONLY if Codemagic docs say this is correct!
      xcode: latest
    scripts:
      - name: Debug JAVA_HOME
        script: |
          #!/bin/bash
          echo "Current JAVA_HOME: $JAVA_HOME"
          java -version # Verify Java is accessible
          javac -version # Verify Java compiler is accessible
      - name: Clean project
        script: ./gradlew clean
      - name: Run KMP Tests
        script: ./gradlew allTests
      - name: Build Android APK
        script: ./gradlew assembleRelease
      - name: Build iOS Framework
        script: ./gradlew :shared:build
    artifacts:
      - build/**/outputs/**/*.apk
      - shared/build/bin/iosArm64/releaseFramework/*.framework
